### ISSUE TITLE
icons button flex left 

### ISSUE THREAD

**Issue by otolaa** [adilkhash/django-trix-editor#1]
![2024-03-02_21-51](https://github.com/adilkhash/django-trix-editor/assets/6308626/9a2a4cd3-def6-4b7e-a0de-5c31bfd513fc)

**Comment by adilkhash** [comment]
Looks like the problem is related to Django >= 5, I will look into it

**Comment by otolaa** [comment]
Django 4.1

**Comment by urba1n** [comment]
Hello, same issue with Django 4.2.11, Chrome 123.0.6312.107

**Comment by adilkhash** [comment]
Let me explore the problem, I will let you know when it is fixed

**Comment by adilkhash** [comment]
Fixed. Please update your package using:
`pip install django-trix-editor==0.3`
